In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

3.0.5
2.5.1

In [3]:
df = pd.read_csv('C:\\nita\\nsutreja_repo\\python-data-engineering\\data\\raw\\production_data.csv')
df.head(5)

,well_id,field_name,operator,basin,well_type,production_date,oil_bbl,gas_mcf,water_bbl,pressure_psi,temperature_f,operating_hours
0,W001,Eagle Ford North,Pioneer Energy,Eagle Ford,Oil,2025-01-01,520,1250,85,3200,145,24
1,W002,Eagle Ford North,Pioneer Energy,Eagle Ford,Oil,2025-01-01,610,1400,92,3150,148,24
2,W003,Permian West,Chevron,Permian,Oil,2025-01-01,730,1800,120,3400,152,24
3,W004,Bakken Central,Continental Resources,Bakken,Oil,2025-01-01,450,900,70,2900,138,22
4,W005,Haynesville East,Chesapeake Energy,Haynesville,Gas,2025-01-01,50,5200,30,4100,160,24

In [4]:
df["production_date"] = pd.to_datetime(df["production_date"])
df.head(5)

,well_id,field_name,operator,basin,well_type,production_date,oil_bbl,gas_mcf,water_bbl,pressure_psi,temperature_f,operating_hours
0,W001,Eagle Ford North,Pioneer Energy,Eagle Ford,Oil,2025-01-01,520,1250,85,3200,145,24
1,W002,Eagle Ford North,Pioneer Energy,Eagle Ford,Oil,2025-01-01,610,1400,92,3150,148,24
2,W003,Permian West,Chevron,Permian,Oil,2025-01-01,730,1800,120,3400,152,24
3,W004,Bakken Central,Continental Resources,Bakken,Oil,2025-01-01,450,900,70,2900,138,22
4,W005,Haynesville East,Chesapeake Energy,Haynesville,Gas,2025-01-01,50,5200,30,4100,160,24

In [7]:
daily_Production = df.groupby('field_name').agg({'oil_bbl': 'sum'}).reset_index() 
print(daily_Production)

         field_name  oil_bbl
0    Bakken Central      895
1  Eagle Ford North     2250
2  Haynesville East      102
3      Permian West     1470

In [ ]:
import requests

from src.config import API_KEY, ENDPOINTS, BASE_URL
endpoint_crude = "crude_production"
endpoint_natural = "natural_gas"

url = f"{BASE_URL}/{ENDPOINTS[endpoint_crude]}"
params = { 
    "api_key": API_KEY
}

response = requests.get(url, params=params, timeout=30)

NameError: name 'requests' is not defined